server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gp15837619548/springcloud-config.git #GitHub 上面的git仓库名字
          ### 搜索目录
          search-paths:
            - springcloud-config
      ### 读取分支
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:7001/eureka
