server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-server1:7001/eureka,http://eureka-server2:7002/eureka  # 集群版