server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/

feign:
  hystrix:
    enabled: true
